<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-JEI8AS0O" ignored="0" name="Test - Firefox" tests="7" failures="2" timestamp="2020-10-17T16:05:41 EDT" time="72.801" errors="0">
  <testcase name="getLocakSystemtime" time="6.657" classname="tests.SystemInfoTest"/>
  <testcase name="getOSInfo" time="5.608" classname="tests.SystemInfoTest"/>
  <testcase name="getLocakSystemtimeSingleBrowser" time="0.268" classname="tests.SystemInfoTestOneBrowser"/>
  <testcase name="getOSInfoSingleBrowsr" time="0.177" classname="tests.SystemInfoTestOneBrowser"/>
  <testcase name="Three" time="0.0" classname="tests.TestScenarioOne">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.TestScenarioOne.Three(TestScenarioOne.java:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Three -->
  <testcase name="testcaseOne" time="2.688" classname="tests.TestScenarioOne"/>
  <testcase name="testCaseTwo" time="3.514" classname="tests.TestScenarioOne">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at tests.TestScenarioOne.testCaseTwo(TestScenarioOne.java:44)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testCaseTwo -->
</testsuite> <!-- Test - Firefox -->
